###
### Demographic Data Implementation Preference
###

subjectDisplayPreferencesProjForm:
  kind: panel.form
  id: subjectDisplayPreferencesProjForm
  name: subjectDisplayPreferencesProjForm
  label: Subject Display Preferences
  method: POST
  contentType: json
  contents:
    ${demographicDataImplProj}
    ${pixiDemographicDataScript}
    ${initDemographicData}

pixiDemographicDataScript:
  tag: script|src="~/scripts/xnat/plugin/pixi/pixi-demographicDataPreference.js"

initDemographicData:
  tag: script
  content: >
    XNAT.plugin.pixi.demographicDataPreferenceManager.init();

demographicDataImplProj:
  kind: panel.select.single
  id: demographicDataImpl
  name: demographicDataImpl
  label: Demographic Data Type Preference
  description: Select a preferred demographic data type to be used when creating new subjects.
  options:
    xnat:
      label: "xnat:demographicData"
      value: "xnat:demographicData"
    pixi:
      label: "pixi:animalDemographicData"
      value: "pixi:animalDemographicData"



#######################################################
####  Root Project Settings Spawner Config Object  ####
#######################################################

projectSettings:
  kind: tabs
  name: pixiProjectPreferencesPage
  label: PIXI Preferences
  meta:
    tabGroups:
      pixiProjectTabGroup: PIXI
  contains: tabs
  tabs:
    projectSubjectSettingsTab:
      kind: tab
      name: projectSubjectSettingsTab
      label: Subject Settings
      group: pixiProjectTabGroup
      active: true
      contents:
        ${subjectDisplayPreferencesProjForm}
