###
### Demographic Data Implementation Preference
###

demographicDataImplForm:
  kind: panel.form
  id: demographicDataImplForm
  name: demographicDataImplForm
  label: Demographic Data Type Preference
  method: PUT
  contentType: json
  url: /xapi/pixi/preferences/demographic-data-impl
  contents:
    ${demographicDataImpl}

demographicDataImpl:
  kind: panel.select.single
  name: demographicDataImpl
  label: Demographic Data Type Preference
  description: Select a preferred demographic data type to be used when creating new subjects.
  options:
    xnat:
      label: "xnat:demographicData"
      value: "xnat:demographicData"
    pixi:
      label: "pixi:animalDemographicData"
      value: "pixi:animalDemographicData"


###
### Species Preferences
###

speciesPreferencesPanel:
  kind: panel
  name: speciesPreferencesPanel
  label: Species
  contents:
    speciesPreferencesTable:
      tag: "div#species-preferences-manager"
    pixiModuleScript:
      tag: script|src="~/scripts/xnat/plugin/pixi/pixi-module.js"
    pixiSpeciesPreferencesScript:
      tag: script|src="~/scripts/xnat/plugin/pixi/pixi-speciesPreferences.js"
    pixiVendorPreferencesScript:
      tag: script|src="~/scripts/xnat/plugin/pixi/pixi-vendorPreferences.js"
    pixiXenograftScripts:
      tag: script|src="~/scripts/xnat/plugin/pixi/pixi-xenograft.js"
    pixiSiteAdminScripts:
      tag: script|src="~/scripts/xnat/plugin/pixi/pixi-siteAdmin.js"

###
### Vendor Preferences
###

vendorPreferencesPanel:
  kind: panel
  name: vendorPreferencesPanel
  label: Animal Vendors / Suppliers
  contents:
    vendorPreferencesTable:
      tag: "div#vendor-preferences-manager"

###
### PDXs
###

pdxPanel:
  kind: panel
  name: pdxPanel
  label: Patient-Derived Xenografts
  contents:
    vendorPreferencesTable:
      tag: "div#pdx-manager"

###
### Cell Lines
###

cellLinePanel:
  kind: panel
  name: cellLinePanel
  label: Cell Line Xenografts
  contents:
    vendorPreferencesTable:
      tag: "div#cell-line-manager"



#################################################
####  Root Site Admin Spawner Config Object  ####
#################################################

siteSettings:
  kind: tabs
  name: pixiAdminPage
  label: Administer PIXI
  meta:
    tabGroups:
      pixiTabGroup: PIXI
  contains: tabs
  tabs:
    subjectSettingsTab:
      kind: tab
      name: subjectSettingsTab
      label: Subject Settings
      group: pixiTabGroup
      active: true
      contents:
        ${demographicDataImplForm}
        ${speciesPreferencesPanel}
        ${vendorPreferencesPanel}
    xenograftSettingsTab:
      kind: tab
      name: xenograftSettingsTab
      label: Xenograft Management
      group: pixiTabGroup
      active: true
      contents:
        ${pdxPanel}
        ${cellLinePanel}

