name: Release

on:
  push:
    branches:
        - releases/v*

jobs:
  release-candidate:

    if: startsWith(github.ref, 'refs/tags/v') and (contains(github.ref, '-rc') || contains(github.ref, '-beta') || contains(github.ref, '-alpha'))

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: jdk

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 6.7

      - name: Build JAR with Gradle Wrapper
        run: ./gradlew clean jar

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          prerelease: true

